export const labels = {
  common: {
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
  },
  portfolio: {
    title: 'Portfolio',
    addAsset: 'Add Asset',
    removeAsset: 'Remove Asset',
    weight: 'Weight',
    allocation: 'Allocation',
    performance: 'Performance',
    risk: 'Risk',
    return: 'Return',
    sharpeRatio: 'Sharpe Ratio',
    beta: 'Beta',
    correlation: 'Correlation',
  },
  risk: {
    title: 'Risk Analysis',
    var: 'Value at Risk',
    cvar: 'Conditional VaR',
    stressTest: 'Stress Test',
    scenarioAnalysis: 'Scenario Analysis',
    confidenceLevel: 'Confidence Level',
    timeHorizon: 'Time Horizon',
  },
  optimization: {
    title: 'Portfolio Optimization',
    efficientFrontier: 'Efficient Frontier',
    maxSharpe: 'Maximum Sharpe Ratio',
    minVariance: 'Minimum Variance',
    maxReturn: 'Maximum Return',
    constraints: 'Constraints',
    rebalance: 'Rebalance',
  },
  settings: {
    title: 'Settings',
    theme: 'Theme',
    currency: 'Currency',
    dataSource: 'Data Source',
    updateFrequency: 'Update Frequency',
    notifications: 'Notifications',
    language: 'Language',
  },
}; 